### ISSUE TITLE
.deb installation throws a scary warning

### ISSUE THREAD

**Issue by luni3359** [hakavlad/nohang#121]
After installing the .deb once apt doesn't complain, but if you try running the reinstall command again you'll get the following "repository broken error":
![Terminal after running the same command a second time](https://user-images.githubusercontent.com/16832398/150618309-caddde43-d970-44dc-990f-8c3f940808e2.png)

It seems it just couldn't calculate the size of the package for whatever reason. 
![Showing the size information with apt](https://user-images.githubusercontent.com/16832398/150618326-15acd4ab-d245-410f-9370-6bb7d0dc7c08.png)

**Comment by hakavlad** [comment]
Thanks for the report. OK, I can reproduce this. It's not a error, just warning:
```
W: Repository is broken: nohang:amd64 (= 0.2.0) has no Size information
```

`has no Size information` is not a real problem: the package is installed correctly, the package manager just does not know its size. This happens because there is no `Installed-Size` field in the file https://github.com/hakavlad/nohang/blob/master/deb/DEBIAN/control.

See also https://man7.org/linux/man-pages/man5/deb-control.5.html.

I don't specify a package size because the size may change after each commit. I'm too lazy to keep track of the package size all the time.

**Comment by luni3359** [comment]
That's very silly. All this time I thought apt automatically calculated the size of the entire package on its own. I know it's a fairly innocent issue but I thought other people might assume the installation broke apt (I did for about 3 seconds).

I'm going to close the issue because this means the scary warning is apt's problem rather than nohang's package.
