### ISSUE TITLE
Notifications don't work.

### ISSUE THREAD

**Issue by Alexey104** [hakavlad/nohang#67]
Hi!
First of all, thanks for nohang! It works fine and does its job perfectly. But notifications don't work for me on Arch. 
'journalctl -eu nohang-desktop' gives me these errors:

```
root : pam_open_session: Permission denied ; TTY=unknown ; PWD=/ ; USER=alexey ; COMMAND=/usr/bin/env DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus,guid=bee7f18339415cb805c5936a5de5fa70 notify-send --icon=dialog-warning Low memory Save your unsaved data!

sudo: setrlimit(RLIMIT_CORE): Operation not permitted

sudo: pam_open_session: Permission denied

pam_limits(sudo:session): Could not set limit for 'memlock': Operation not permitted

sudo: policy plugin failed session initialization
```

How can i fix this?
Thanks!

**Comment by hakavlad** [comment]
Hi! Thank you for the report! I also noticed this problem in recent versions. I will look for a reason.

**Comment by Alexey104** [comment]
I found that notifications work fine if i start nohang via '~/.config/i3/config' or '~/.Xinitrc' instead of starting it as systemd daemon.

**Comment by hakavlad** [comment]
No problem with latest nohang v0.1-517-g51c3bc7 on Manjaro: https://imgur.com/a/Ga9e41y.

I've seen this bug on Fedora: https://github.com/hakavlad/nohang/issues/61

No problem on my Debian.

>instead of starting it as systemd daemon.

I guess the problem is restrictions in the systemd unit: https://github.com/hakavlad/nohang/blob/master/nohang/nohang-desktop.service.in

>setrlimit(RLIMIT_CORE): Operation not permitted

Maybe this needs CAP_SYS_RESOURCE. Could you add it in nohang-daemon.service and run `# systemctl daemon-reload && systemctl nohang-desktop restart`?

**Comment by Alexey104** [comment]
> Maybe this needs CAP_SYS_RESOURCE. Could you add it in nohang-daemon.service and run # systemctl daemon-reload && systemctl nohang-desktop restart and make memory stress test?

That solved the issue!
Thanks a lot for your help!

**Comment by hakavlad** [comment]
Thank you! https://github.com/hakavlad/nohang/commit/93a504a5ce23f2960bf7bff28496956ae457d5fe
